cmake_minimum_required(VERSION 3.10)
project(libipc C CXX)
include(./../cmake/arm-flags.cmake)
file(GLOB_RECURSE SOURCES "src/*.cpp" "src/*.c")
file(GLOB_RECURSE HEADERS "include/*.h" "include/*.hpp")
set(INCLUDE_DIRS "")
foreach(HEADER_FILE ${HEADERS})
    get_filename_component(DIR_PATH ${HEADER_FILE} DIRECTORY)
    list(APPEND INCLUDE_DIRS ${DIR_PATH})
endforeach()
list(REMOVE_DUPLICATES INCLUDE_DIRS)
add_library(libipc STATIC ${SOURCES})
set_target_properties(libipc PROPERTIES OUTPUT_NAME "ipc")
target_include_directories(libipc PUBLIC ${INCLUDE_DIRS})
