cmake_minimum_required(VERSION 3.10)
project(intercom_gpio_demon C CXX)
include(./../cmake/arm-flags.cmake)

file(GLOB EXTERNAL_ITEMS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "external/*")
foreach(ITEM ${EXTERNAL_ITEMS})
    if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${ITEM}" AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${ITEM}/CMakeLists.txt")
        add_subdirectory(${ITEM})
    endif()
endforeach()

file(GLOB_RECURSE SOURCES "src/*.cpp" "src/*.c")
file(GLOB_RECURSE HEADERS "include/*.h" "include/*.hpp")
set(INCLUDE_DIRS "")
foreach(HEADER_FILE ${HEADERS})
    get_filename_component(DIR_PATH ${HEADER_FILE} DIRECTORY)
    list(APPEND INCLUDE_DIRS ${DIR_PATH})
endforeach()
list(REMOVE_DUPLICATES INCLUDE_DIRS)
add_executable(intercom_gpio_demon ${SOURCES})
target_include_directories(intercom_gpio_demon PUBLIC ${INCLUDE_DIRS})
find_package(Threads REQUIRED)
target_link_libraries(intercom_gpio_demon PRIVATE pigpio libipc Threads::Threads rt)